name: Build and deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get code from (${{ steps.extract_branch.outputs.branch }})
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Install dependencies
        run: npm install
        # working-directory: wear-front
      - name: Remove old builds
        run: rm -rf build.zip build || true
      - name: Build project
        run: CI=false npm run build
        # working-directory: wear-front
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # path: wear-front/build
          path: build
          name: build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build project
        uses: actions/download-artifact@v4
        with:
          name: build

